---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-apid-opts-data-pvc
  namespace: jhub
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Gi
  storageClassName: csi-s3
