---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-prj-002-data-pvc
  namespace: jhub
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: csi-s3
