---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-apid-amexw-data-pvc
  namespace: jhub
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Gi
  storageClassName: csi-s3
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000    
