apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-shared-pv
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.0
    - timeo=60
    - retrans=10
  capacity:
    storage: 64Gi
  nfs:
    server: 10.0.0.15
    path: "/shares/share-e2f00bbd-e5d2-4d16-b10a-4b8988a0e001"
  persistentVolumeReclaimPolicy: "Recycle"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared-pvc
  namespace: jhub
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  volumeName: "jupyterhub-shared-pv"
  storageClassName: ""
