apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubdrain-serviceaccount
  namespace: jhub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubdrain-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hubdrain-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: hubdrain-serviceaccount
  namespace: jhub
roleRef:
  kind: ClusterRole
  name: hubdrain-clusterrole
  apiGroup: rbac.authorization.k8s.io